import { AlertTriangle } from "lucide-react";

export function DisclaimerFooter() {
  return (
    <footer className="sticky bottom-0 z-20 border-t border-slate-700/50 bg-slate-800/80 backdrop-blur-xl">
      <div className="flex items-center justify-center gap-2 px-4 py-2">
        <AlertTriangle className="h-4 w-4 flex-shrink-0 text-amber-500" />
        <p className="text-center text-xs text-slate-400">
          <span className="font-medium text-amber-500">Disclaimer:</span>{" "}
          Information generated by this application should not be considered 100% reliable.
          Use only as a cross-check. Traditional methods and procedures are still advised and applicable.
        </p>
      </div>
    </footer>
  );
}

export default DisclaimerFooter;
